### ISSUE TITLE
Performance is not defined

### ISSUE THREAD

**Issue by daisyxu0924** [sinonjs/lolex#171]
Hello, I'm getting
 ``` ReferenceError: Performance is not defined
      at createClock (node_modules/lolex/src/lolex-src.js:736:36)
      at Object.install (node_modules/lolex/src/lolex-src.js:791:21)
      at Sandbox.exports.useFakeTimers (node_modules/sinon/lib/sinon/util/fake_timers.js:26:21)
```
with the new release 2.4.1. 

```
├─┬ sinon@4.5.0
│ ├─┬ @sinonjs/formatio@2.0.0
│ │ └── samsam@1.3.0
│ ├── lodash.get@4.4.2
│ ├── lolex@2.4.1
```
When used lolex@2.3.2 it was working fine.

Thanks!

**Comment by benjamingr** [comment]
Hey, apologies! @daisyxu0924 

Can you please share what browser you're seeing this in?

**Comment by daisyxu0924** [comment]
Hello @benjamingr sorry about the late reply. my useragent is 
```Mozilla/5.0 (darwin) AppleWebKit/537.36 (KHTML, like Gecko) jsdom/11.7.0```
I've updated lolex to 2.5.0 global.Performance is still undefined. Thanks!

**Comment by phoebejhhong** [comment]
Hey I'm working on the same project with @daisyxu0924

The code that invokes this problem is just
```js
sinon.useFakeTimers(Date.now())
```

as part of our test suite along with mocha, enzyme and webpack.
I've found the commit that caused problem for us (https://github.com/sinonjs/lolex/commit/469b547334aeee8731581a24b8e42fb23d2aea43) and when we comment that block of code out, everything is fine. After version 2.4.2, the error message was updated to`TypeError: Cannot read property 'prototype' of undefined` because `global.Performance` is undefined.

**Comment by dwoowb** [comment]
@daisyxu0924 I'm running into what looks like the same issue. Could you elaborate a bit on how jsdom was related to this issue for you? Thank you!

**Comment by daisyxu0924** [comment]
Hi @dwoowb we are using enzyme + jsdom and running tests in node env. So what we did was overriding the node global env with jsom (which is not recommended by jsdom btw). So when lolex is executing global.Performance it's actually reading the node env. If yours is the same case, have a look at this: https://github.com/airbnb/enzyme/blob/master/docs/guides/jsdom.md

**Comment by panzerdp** [comment]
Experiencing the same problem as the author describes. My setup is Node v8.5.0, jsdom@11.10.0, mocha@5.1.1 and sinon@5.0.7.
The error disappeared only after indication in `package.json` to install lolex@2.3.2.

**Comment by fatso83** [comment]
Also with 2.5?

**Comment by panzerdp** [comment]
@fatso83,
When using lolex@2.5.0 I have the following error:
```
TypeError: Cannot read property 'prototype' of undefined
      at createClock (node_modules/lolex/src/lolex-src.js:749:44)
      at Object.install (node_modules/lolex/src/lolex-src.js:806:21)
      at exports.useFakeTimers (node_modules/sinon/lib/sinon/util/fake_timers.js:26:21)
      at Context.<anonymous> (app/components/Component/tests/index.test.jsx:28:19)
```

**Comment by fatso83** [comment]
@panzerdp As this is closed, and most issues we have seen mentioned here seems to be due to something else and fixed, could you please open a PR and try to make a _minimal_, reproducible case? As the test and build steps at Travis are fine, it's clear that we are not catching it in our tests, and I wouldn't know what the problem is or how to test for it (or its resolution).

The best solution would of course be if you could find the bug yourself, or which commit introduced it ... :pray: In which case I advice you to check out [these git bisect templates](https://github.com/fatso83/git-bisect-scripts) I use myself to quickly find regresions in Sinon. You can use your own project as the test for the bug (read the source).

---
[Background on Git bisect](http://www.marclittlemore.com/how-to-find-bugs-using-git-bisect-with-this-easy-guide/)

**Comment by fatso83** [comment]
P.S. @benjamingr You might want to check out those scripts as well, as they have made life as a regression hunter much easier in the past :smiley_cat:

**Comment by panzerdp** [comment]
@fatso83,
The problem was introduced by [this commit](https://github.com/sinonjs/lolex/commit/469b547334aeee8731581a24b8e42fb23d2aea43).

**Comment by fatso83** [comment]
Weird. We only check that `global.performance` is defined, not `Performance`. Seems like we missed a check.

**Comment by benjamingr** [comment]
@fatso83 on it

**Comment by benjamingr** [comment]
https://github.com/sinonjs/lolex/pull/181

**Comment by fatso83** [comment]
@panzerdp As #181 discusses, we could need some more information on this regarding browsers affected. Could you tell us which browser/environment this bug appears?

**Comment by panzerdp** [comment]
@fatso83,
Please check [this comment](https://github.com/sinonjs/lolex/issues/171#issuecomment-389412273).  

I actually run some React unit tests in JSDOM environment. You can [see here](https://github.com/jsdom/jsdom/blob/master/lib/jsdom/browser/Window.js#L158) what properties exposes JSDOM's window object (`performance` is exposed, while `Performance` is not).
