### ISSUE TITLE
TypeError: Cannot set property performance of #<Object> which has only a getter

### ISSUE THREAD

**Issue by daisyxu0924** [sinonjs/lolex#197]
> We understand you have a problem and are in a hurry, but please provide us with some info to make it much more likely for your issue to be understood, worked on and resolved quickly.

* Lolex version : 2.7.1
* Environment   : jsdom window
* Example URL   : 
* Other libraries you are using:

**What did you expect to happen?**

**What actually happens**
Hello, we use sinon's useFakeTimers after copying jsdom window to global following this method https://github.com/airbnb/enzyme/blob/master/docs/guides/jsdom.md

after https://github.com/sinonjs/lolex/commit/79f9431a7278509ebffbe107484f521f76b3f665 this commit, it's complaining:

```
TypeError: Cannot set property performance of #<Object> which has only a getter
      at hijackMethod (node_modules/lolex/src/lolex-src.js:445:28)
      at Object.install (node_modules/lolex/src/lolex-src.js:844:17)
      at exports.useFakeTimers (node_modules/sinon/lib/sinon/util/fake_timers.js:26:21) 
```

and 

```
TypeError: Cannot assign to read only property 'performance' of object '#<Object>'
      at uninstall (node_modules/lolex/src/lolex-src.js:408:32)
      at Object.clock.uninstall (node_modules/lolex/src/lolex-src.js:817:20)
```

 To be honest I'm not sure if I should be asking JSDOM to fix the window object or should lolex's code handle this scenario, anyway I'll just post this issue here first. 

Thanks!
**How to reproduce**
> Describe *with code* how to reproduce the faulty behaviour
> or link to code on JSBin or similar

<details>
    <summary>Really long code sample or stacktrace</summary>

    If you need to provide a dump of a stack trace or
    other lengthy material, such as 80 lines of example code,
    please stuff it in a `<details>` tag such as this
    to make the issue more readable. Thanks.
</details>

**Comment by philostler** [comment]
Just bumped into the same issue here. @daisyxu0924 can you please cross reference that issue JSDOM if you've created one

**Comment by fatso83** [comment]
Seems solved by #199

**Comment by shockey** [comment]
I'm seeing a very similar error with `lolex@3.0.0`:

```
     TypeError: Cannot set property performance of #<Object> which has only a getter
      at hijackMethod (node_modules/lolex/src/lolex-src.js:445:28)
      at Object.install (node_modules/lolex/src/lolex-src.js:877:17)
      at createClock (node_modules/sinon/lib/sinon/util/fake-timers.js:11:24)
      at exports.useFakeTimers (node_modules/sinon/lib/sinon/util/fake-timers.js:27:16)
      at Sandbox.useFakeTimers (node_modules/sinon/lib/sinon/sandbox.js:333:46)
      at Context.<anonymous> (test/core/plugins/samples/fn.js:249:25)
```

**Comment by fatso83** [comment]
@shockey: this issue is closed. Please open a new one containing a reproducible test case. Try RunKit.

**Comment by fatso83** [comment]
@cptbob42 and @shockey , we just got a reproducible case of a similar looking issue in #243. You might want to latch onto that.
